### ISSUE TITLE
Site title doesn't fit the container

### ISSUE THREAD

**Issue by awulkan** [software-architects/learn-blazor#1]
Just wanted to point out that the site title doesn't fit its container. Maybe you should use plain text instead of an image. :)

![image](https://i.imgur.com/CcZAQ5p.png)

Great initiative with the website btw.

**Comment by rstropek** [comment]
Thank you for letting me know. The SVG had text in it which did not correctly render in your browser. I made a change. Could you check again and give me feedback?

Thank you, greetings,
Rainer.

**Comment by awulkan** [comment]
Yep, it fits now. Closing this issue. :)

![img](https://i.imgur.com/yX27Jre.png)
